Repository ManageIQ/container-httpd-init, pull requests merged in 2022-02, with the labels that each got.

#18 Switch to GitHub Actions
  .github/workflows/ci.yaml
  .travis.yml
  bin/build_container_image
Labels: developer

#19 Bump ubi to 8.5
  Dockerfile
Labels: enhancement

#21 Fix branches in forks from failing
  .github/workflows/ci.yaml
  bin/build_container_image
Labels: bug
